spring:
  application:
    name: auth-service
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${random.value}
logging:
  level:
    root: INFO
    com.cts: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: mySecretKeyForJwtTokenGenerationWhichIsLongEnoughToBeSecure123456789
  expiration: 36000000